### ISSUE TITLE
Screenshot for README

### ISSUE THREAD

**Issue by luzpaz** [prrvchr/USBTerminal#1]
Thanks! 👍

**Comment by luzpaz** [comment]
@prrvchr does this WB still work ?

**Comment by prrvchr** [comment]
Yes it does...

**Comment by luzpaz** [comment]
CC @sliptonic

**Comment by luzpaz** [comment]
@prrvchr is this compatible with FC 0.17 ?
Also would you be OK adding this to the [FreeCAD-addons](https://github.com/FreeCAD/FreeCAD-addons) repo ?

**Comment by prrvchr** [comment]
>  is this compatible with FC 0.17 ?

I'm sure it works under FC 0.16, it should test for 0.17, but I assume it works.

> Also would you be OK adding this to the FreeCAD-addons repo ?

Why not, but this is experimental ... :-)

**Comment by luzpaz** [comment]
CC @mlampert

**Comment by mlampert** [comment]
I have no way of testing this, it's not integrated with the Path WB, if I read the code correctly it will upload a file from disk.
