### ISSUE TITLE
any progress?

### ISSUE THREAD

**Issue by luzpaz** [prrvchr/USBTerminal#2]

**Comment by prrvchr** [comment]
Hi Luzpaz,

I need to finish an extension for OpenOffice, and I come back for USBTerminal...

**Comment by Xav83130** [comment]
Good New !!!!

**Comment by luzpaz** [comment]
@prrvchr any news?

**Comment by prrvchr** [comment]
Hi luzpaz,

Sorry to ask this but what should we do with USBTerminal?

**Comment by luzpaz** [comment]
I was wondering if there is still a usecase for it

**Comment by prrvchr** [comment]
I think today it is obsolete
